dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: node-http3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: goland-http5
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
